-- SPDX-License-Identifier: Unlicense

g_cmd = '?pathfind'
g_announce_name = '[PathfindPlus]'
g_pf = nil

function onCustomCommand(full_message, user_peer_id, is_admin, is_auth, cmd, target_x, target_z, ...)
    if cmd ~= g_cmd then
        return
    end

    target_x = tonumber(target_x)
    target_z = tonumber(target_z)
    if target_x == nil or target_z == nil then
        server.announce(g_announce_name, 'error: invalid argument', user_peer_id)
        return
    end

    local target_pos = matrix.translation(target_x, 0, target_z)
    local player_pos, is_success = server.getPlayerPos(user_peer_id)
    if not is_success then
        server.announce(g_announce_name, 'error: failed to retrieve player position', user_peer_id)
        return
    end

    server.removeMapObject(user_peer_id, g_savedata['ui_id'])
    server.removeMapLine(user_peer_id, g_savedata['ui_id'])

    local player_x, _, player_z = matrix.position(player_pos)
    server.addMapObject(user_peer_id, g_savedata['ui_id'], 0, 1, player_x, player_z, 0, 0, 0, 0, 'matrix_start', 0, '')
    server.addMapObject(user_peer_id, g_savedata['ui_id'], 0, 0, target_x, target_z, 0, 0, 0, 0, 'matrix_end', 0, '')

    local path = g_pf:pathfindOcean(player_pos, target_pos)
    local prev_pos = player_pos
    for i, _ in ipairs(path) do
        local next_pos = matrix.translation(path[i]['x'], 0, path[i]['z'])
        server.addMapLine(user_peer_id, g_savedata['ui_id'], prev_pos, next_pos, 1)
        prev_pos = next_pos
    end
end

function onCreate(is_world_create)
    local version = 0
    if type(g_savedata) ~= 'table' or g_savedata['version'] ~= version then
        g_savedata = {
            ['version'] = version,
            ['ui_id'] = server.getMapID(),
        }
    end

    g_pf = buildPathfinder()
end

function buildPathfinder()
    local pf = {
        _world_x1 = -64000,
        _world_z1 = -64000,
        _world_x2 = 64000,
        _world_z2 = 128000,
        _tile_size = 500,
        _joint_tbl = {},
        _tile_list = {},
        _node_list = {},
        _num_perm_node = 0,
        _start_node_idx = nil,
        _end_node_idx = nil,
    }

    function pf:pathfindOcean(matrix_start, matrix_end)
        local start_x, _, start_z = matrix.position(matrix_start)
        local end_x, _, end_z = matrix.position(matrix_end)

        self:_reset()
        self._start_node_idx = self:_addTempNode(start_x, start_z)
        self._end_node_idx = self:_addTempNode(end_x, end_z)
        self:_calcPath()
        return self:_getPathList()
    end

    function pf:_init()
        self._joint_tbl = {}
        self._tile_list = {}
        self._node_list = {}
        self._num_perm_node = 0
        self._start_node_idx = nil
        self._end_node_idx = nil
        if self._world_x1%1 ~= 0 or self._world_z1%1 ~= 0 or self._world_x2%1 ~= 0 or self._world_z2%1 ~= 0 or self._tile_size%1 ~= 0 then
            return
        end

        self:_initJointTable()
        self:_initTileList()
        self:_initNodeList()
    end

    function pf:_initJointTable()
        self._joint_tbl = {
            -- begin code generated by pfpjoint
            ['data/tiles/arctic_island_oil_refinery.xml'] = {[1] = true},
            ['data/tiles/arctic_island_playerbase.xml'] = {[3] = true, [6] = true},
            ['data/tiles/arctic_island_shipbreaking.xml'] = {[2] = true, [8] = true},
            ['data/tiles/arctic_tile_11.xml'] = {[2] = true, [3] = true, [4] = true, [6] = true},
            ['data/tiles/arctic_tile_12_oilrig.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true},
            ['data/tiles/arctic_tile_13.xml'] = {[1] = true, [2] = true, [4] = true},
            ['data/tiles/arctic_tile_21.xml'] = {[2] = true, [3] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/arctic_tile_22.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/arctic_tile_23.xml'] = {[1] = true, [2] = true, [4] = true, [7] = true, [8] = true},
            ['data/tiles/arctic_tile_31.xml'] = {[6] = true, [8] = true, [9] = true},
            ['data/tiles/arctic_tile_32.xml'] = {[2] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/arctic_tile_33.xml'] = {[4] = true, [7] = true, [8] = true},
            ['data/tiles/island11.xml'] = {[8] = true},
            ['data/tiles/island12.xml'] = {[2] = true},
            ['data/tiles/island_33_tile_03.xml'] = {[1] = true, [2] = true, [6] = true},
            ['data/tiles/island_33_tile_04.xml'] = {[1] = true, [4] = true, [6] = true, [8] = true},
            ['data/tiles/island_33_tile_05.xml'] = {[4] = true, [6] = true},
            ['data/tiles/island_33_tile_06.xml'] = {[4] = true, [6] = true},
            ['data/tiles/island_33_tile_07.xml'] = {[4] = true, [6] = true},
            ['data/tiles/island_33_tile_08.xml'] = {[3] = true, [4] = true, [6] = true},
            ['data/tiles/island_33_tile_09.xml'] = {[2] = true, [4] = true},
            ['data/tiles/island_33_tile_11.xml'] = {[2] = true, [3] = true, [6] = true},
            ['data/tiles/island_33_tile_12.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [9] = true},
            ['data/tiles/island_33_tile_13.xml'] = {[1] = true, [2] = true, [4] = true, [8] = true, [9] = true},
            ['data/tiles/island_33_tile_21.xml'] = {[2] = true, [3] = true, [6] = true, [8] = true, [9] = true},
            ['data/tiles/island_33_tile_22.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/island_33_tile_23.xml'] = {[1] = true, [2] = true, [4] = true, [7] = true, [8] = true},
            ['data/tiles/island_33_tile_31.xml'] = {[6] = true, [8] = true, [9] = true},
            ['data/tiles/island_33_tile_32.xml'] = {[4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/island_33_tile_33.xml'] = {[4] = true, [7] = true, [8] = true},
            ['data/tiles/island_33_tile_end.xml'] = {[7] = true, [8] = true},
            ['data/tiles/island_37_container_depot.xml'] = {[3] = true},
            ['data/tiles/island_41_underwater_mining.xml'] = {[1] = true},
            ['data/tiles/island_42_volcano_tile_11.xml'] = {[2] = true, [3] = true, [6] = true},
            ['data/tiles/island_42_volcano_tile_12.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true},
            ['data/tiles/island_42_volcano_tile_13.xml'] = {[1] = true, [2] = true, [4] = true},
            ['data/tiles/island_42_volcano_tile_21.xml'] = {[2] = true, [3] = true, [6] = true, [8] = true, [9] = true},
            ['data/tiles/island_42_volcano_tile_22.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/island_42_volcano_tile_23.xml'] = {[1] = true, [2] = true, [4] = true, [7] = true, [8] = true},
            ['data/tiles/island_42_volcano_tile_31.xml'] = {[6] = true, [8] = true, [9] = true},
            ['data/tiles/island_42_volcano_tile_32.xml'] = {[4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/island_42_volcano_tile_33.xml'] = {[4] = true, [7] = true, [8] = true},
            ['data/tiles/mega_island_0_0.xml'] = {[6] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_0_1.xml'] = {[2] = true, [3] = true, [6] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_0_2.xml'] = {[2] = true, [3] = true, [6] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_0_3.xml'] = {[2] = true, [3] = true, [6] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_0_4.xml'] = {[2] = true, [3] = true, [6] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_0_5.xml'] = {[2] = true, [3] = true, [6] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_0_6.xml'] = {[2] = true, [3] = true, [6] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_0_7.xml'] = {[2] = true, [3] = true, [6] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_0_8.xml'] = {[2] = true, [3] = true, [6] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_0_9.xml'] = {[2] = true, [3] = true, [6] = true},
            ['data/tiles/mega_island_10_1.xml'] = {[3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_10_2.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_10_3.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_10_4.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_10_5.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_10_6.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_10_7.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_10_8.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_10_9.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true},
            ['data/tiles/mega_island_11_0.xml'] = {[6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_11_1.xml'] = {[2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_11_2.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_11_3.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_11_4.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_11_5.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_11_6.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_11_7.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_11_8.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_11_9.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [8] = true},
            ['data/tiles/mega_island_12_0.xml'] = {[4] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_12_1.xml'] = {[1] = true, [2] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_12_2.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_12_3.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_12_4.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_12_5.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_12_6.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_12_7.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_12_8.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_12_9.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true},
            ['data/tiles/mega_island_13_1.xml'] = {[1] = true, [3] = true, [4] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_13_2.xml'] = {[1] = true, [2] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_13_3.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_13_4.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_13_5.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_13_6.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_13_7.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_13_8.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_13_9.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true},
            ['data/tiles/mega_island_14_0.xml'] = {[6] = true, [7] = true, [9] = true},
            ['data/tiles/mega_island_14_2.xml'] = {[1] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_14_3.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_14_4.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_14_5.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_14_6.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_14_7.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_14_8.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true},
            ['data/tiles/mega_island_14_9.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true},
            ['data/tiles/mega_island_15_0.xml'] = {[4] = true, [6] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_15_1.xml'] = {[1] = true, [2] = true, [3] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_15_2.xml'] = {[2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_15_3.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_15_4.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_15_5.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_15_6.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_15_7.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_15_8.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true},
            ['data/tiles/mega_island_16_0.xml'] = {[4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_16_1.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_16_2.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_16_3.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_16_4.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_16_5.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_16_6.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_16_7.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_16_8.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true},
            ['data/tiles/mega_island_17_0.xml'] = {[4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_17_1.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_17_2.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_17_3.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_17_4.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_17_5.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_17_6.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_17_7.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true},
            ['data/tiles/mega_island_17_8.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true},
            ['data/tiles/mega_island_18_0.xml'] = {[4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_18_1.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_18_2.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_18_3.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_18_4.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_18_5.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_18_6.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_18_7.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true},
            ['data/tiles/mega_island_19_0.xml'] = {[4] = true, [7] = true, [8] = true},
            ['data/tiles/mega_island_19_1.xml'] = {[1] = true, [2] = true, [4] = true, [7] = true, [8] = true},
            ['data/tiles/mega_island_19_2.xml'] = {[1] = true, [2] = true, [4] = true, [7] = true, [8] = true},
            ['data/tiles/mega_island_19_3.xml'] = {[1] = true, [2] = true, [4] = true, [7] = true, [8] = true},
            ['data/tiles/mega_island_19_4.xml'] = {[1] = true, [2] = true, [4] = true, [7] = true, [8] = true},
            ['data/tiles/mega_island_19_5.xml'] = {[1] = true, [2] = true, [4] = true, [7] = true, [8] = true},
            ['data/tiles/mega_island_19_6.xml'] = {[1] = true, [2] = true, [4] = true, [7] = true, [8] = true},
            ['data/tiles/mega_island_19_7.xml'] = {[1] = true, [2] = true, [4] = true},
            ['data/tiles/mega_island_1_0.xml'] = {[4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_1_1.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_1_2.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_1_3.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_1_4.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_1_5.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_1_6.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_1_7.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_1_8.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_1_9.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true},
            ['data/tiles/mega_island_2_0.xml'] = {[4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_2_1.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_2_2.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_2_3.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_2_4.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_2_5.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_2_6.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_2_7.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_2_8.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_2_9.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true},
            ['data/tiles/mega_island_3_0.xml'] = {[4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_3_1.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_3_2.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_3_3.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_3_4.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_3_5.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_3_6.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_3_7.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_3_8.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_3_9.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true},
            ['data/tiles/mega_island_4_0.xml'] = {[4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_4_1.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_4_2.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_4_3.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_4_4.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_4_5.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_4_6.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_4_7.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_4_8.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_4_9.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true},
            ['data/tiles/mega_island_5_0.xml'] = {[4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_5_1.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_5_2.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_5_3.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_5_4.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_5_5.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_5_6.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_5_7.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_5_8.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_5_9.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true},
            ['data/tiles/mega_island_6_0.xml'] = {[4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_6_1.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_6_2.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_6_3.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_6_4.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_6_5.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_6_6.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_6_7.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_6_8.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_6_9.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true},
            ['data/tiles/mega_island_7_0.xml'] = {[4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_7_1.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_7_2.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_7_3.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_7_4.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_7_5.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_7_6.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_7_7.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_7_8.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_7_9.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true},
            ['data/tiles/mega_island_8_0.xml'] = {[4] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_8_1.xml'] = {[1] = true, [2] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_8_2.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_8_3.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_8_4.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_8_5.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_8_6.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_8_7.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_8_8.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_8_9.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true},
            ['data/tiles/mega_island_9_1.xml'] = {[1] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_9_2.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_9_3.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_9_4.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_9_5.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_9_6.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_9_7.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_9_8.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true, [7] = true, [8] = true, [9] = true},
            ['data/tiles/mega_island_9_9.xml'] = {[1] = true, [2] = true, [3] = true, [4] = true, [6] = true},
            ['data/tiles/track_curve_left_diagonal_rot_0.xml'] = {[2] = true, [7] = true},
            ['data/tiles/track_curve_left_diagonal_rot_1.xml'] = {[4] = true, [9] = true},
            ['data/tiles/track_curve_left_diagonal_rot_2.xml'] = {[3] = true, [8] = true},
            ['data/tiles/track_curve_left_diagonal_rot_3.xml'] = {[1] = true, [6] = true},
            ['data/tiles/track_curve_right_diagonal_rot_0.xml'] = {[2] = true, [9] = true},
            ['data/tiles/track_curve_right_diagonal_rot_1.xml'] = {[3] = true, [4] = true},
            ['data/tiles/track_curve_right_diagonal_rot_2.xml'] = {[1] = true, [8] = true},
            ['data/tiles/track_curve_right_diagonal_rot_3.xml'] = {[6] = true, [7] = true},
            ['data/tiles/track_curve_right_diagonal_variant_rot_0.xml'] = {[2] = true, [9] = true},
            ['data/tiles/track_curve_right_diagonal_variant_rot_1.xml'] = {[3] = true, [4] = true},
            ['data/tiles/track_curve_right_diagonal_variant_rot_2.xml'] = {[1] = true, [8] = true},
            ['data/tiles/track_curve_right_diagonal_variant_rot_3.xml'] = {[6] = true, [7] = true},
            ['data/tiles/track_diagonal_left.xml'] = {[3] = true, [7] = true},
            ['data/tiles/track_diagonal_left_fork_straight_rot_0.xml'] = {[3] = true, [7] = true, [8] = true},
            ['data/tiles/track_diagonal_left_fork_straight_rot_1.xml'] = {[1] = true, [4] = true, [9] = true},
            ['data/tiles/track_diagonal_left_fork_straight_rot_2.xml'] = {[2] = true, [3] = true, [7] = true},
            ['data/tiles/track_diagonal_left_fork_straight_rot_3.xml'] = {[1] = true, [4] = true, [9] = true},
            ['data/tiles/track_diagonal_right.xml'] = {[1] = true, [9] = true},
            ['data/tiles/track_diagonal_right_fork_straight_rot_0.xml'] = {[1] = true, [8] = true, [9] = true},
            ['data/tiles/track_diagonal_right_fork_straight_rot_1.xml'] = {[3] = true, [6] = true, [7] = true},
            ['data/tiles/track_diagonal_right_fork_straight_rot_2.xml'] = {[1] = true, [2] = true, [9] = true},
            ['data/tiles/track_diagonal_right_fork_straight_rot_3.xml'] = {[3] = true, [4] = true, [7] = true},
            ['data/tiles/track_diagonal_variant_rot_0.xml'] = {[3] = true, [7] = true},
            ['data/tiles/track_diagonal_variant_rot_1.xml'] = {[1] = true, [9] = true},
            ['data/tiles/track_straight.xml'] = {[2] = true, [8] = true},
            ['data/tiles/track_straight_fork_left_rot_0.xml'] = {[2] = true, [7] = true, [8] = true},
            ['data/tiles/track_straight_fork_left_rot_1.xml'] = {[4] = true, [6] = true, [9] = true},
            ['data/tiles/track_straight_fork_left_rot_2.xml'] = {[2] = true, [3] = true, [8] = true},
            ['data/tiles/track_straight_fork_left_rot_3.xml'] = {[1] = true, [4] = true, [6] = true},
            ['data/tiles/track_straight_fork_right_rot_0.xml'] = {[2] = true, [8] = true, [9] = true},
            ['data/tiles/track_straight_fork_right_rot_1.xml'] = {[3] = true, [4] = true, [6] = true},
            ['data/tiles/track_straight_fork_right_rot_2.xml'] = {[1] = true, [2] = true, [8] = true},
            ['data/tiles/track_straight_fork_right_rot_3.xml'] = {[4] = true, [6] = true, [7] = true},
            ['data/tiles/track_straight_horizontal.xml'] = {[4] = true, [6] = true},
            ['data/tiles/track_straight_variant_rot_0.xml'] = {[2] = true, [8] = true},
            ['data/tiles/track_straight_variant_rot_1.xml'] = {[4] = true, [6] = true},
            -- end code generated by pfpjoint
        }
    end

    function pf:_initTileList()
        self._tile_list = {}
        for x = self._world_x1, self._world_x2, self._tile_size*2 do
            for z = self._world_z1, self._world_z2, self._tile_size*2 do
                local _, is_success = server.getOceanTransform(matrix.translation(x, 0, z), 0, 1)
                if is_success then
                    goto continue
                end
                local tile_data, is_success = server.getTile(matrix.translation(x, 0, z))
                if not is_success then
                    goto continue
                end

                table.insert(self._tile_list, {
                    x = x,
                    z = z,
                    joint = self._joint_tbl[tile_data['name']] or {},
                })
                ::continue::
            end
        end
    end

    function pf:_initNodeList()
        local tile_tbl = {}
        for tile_idx, tile in pairs(self._tile_list) do
            tile_tbl[tile.x] = tile_tbl[tile.x] or {}
            tile_tbl[tile.x][tile.z] = tile_idx
        end

        self._node_list = {}
        for x = self._world_x1 - self._tile_size, self._world_x2 + self._tile_size, self._tile_size*2 do
            for z = self._world_z1 - self._tile_size, self._world_z2 + self._tile_size, self._tile_size*2 do
                local ok = true
                for _, joint_idx in pairs({1, 3, 7, 9}) do
                    local tile_x = x + self._tile_size*((joint_idx - 1)%3 - 1)
                    local tile_z = z + self._tile_size*((joint_idx - 1)//3 - 1)
                    local tile_idx = (tile_tbl[tile_x] or {})[tile_z]
                    if tile_idx ~= nil and self._tile_list[tile_idx].joint[10 - joint_idx] then
                        ok = false
                        break
                    end
                end
                if ok then
                    table.insert(self._node_list, {
                        x = x,
                        z = z,
                        edge_tbl = nil,
                        cost = nil,
                        prev = nil,
                        visited = false,
                    })
                end
            end
        end
        self._num_perm_node = #self._node_list

        local node_tbl = {}
        for node_idx, node in pairs(self._node_list) do
            node_tbl[node.x] = node_tbl[node.x] or {}
            node_tbl[node.x][node.z] = node_idx
        end

        for _, this_node in pairs(self._node_list) do
            local joint = {}
            for _, joint_idx in pairs({1, 3, 7, 9}) do
                local tile_x = this_node.x + self._tile_size*((joint_idx - 1)%3 - 1)
                local tile_z = this_node.z + self._tile_size*((joint_idx - 1)//3 - 1)
                if (tile_tbl[tile_x] or {})[tile_z] == nil then
                    joint[joint_idx] = true
                end
            end
            for _, joint_idx in pairs({2, 8}) do
                local e_tile_x = this_node.x + self._tile_size
                local e_tile_z = this_node.z + self._tile_size*((joint_idx - 1)//3 - 1)
                local e_tile_idx = (tile_tbl[e_tile_x] or {})[e_tile_z]
                local e_tile = e_tile_idx ~= nil and self._tile_list[e_tile_idx] or nil
                local w_tile_x = this_node.x - self._tile_size
                local w_tile_z = this_node.z + self._tile_size*((joint_idx - 1)//3 - 1)
                local w_tile_idx = (tile_tbl[w_tile_x] or {})[w_tile_z]
                local w_tile = w_tile_idx ~= nil and self._tile_list[w_tile_idx] or nil
                if (e_tile == nil or not e_tile.joint[4]) and (w_tile == nil or not w_tile.joint[6]) then
                    joint[joint_idx] = true
                end
            end
            for _, joint_idx in pairs({4, 6}) do
                local n_tile_x = this_node.x + self._tile_size*((joint_idx - 1)%3 - 1)
                local n_tile_z = this_node.z + self._tile_size
                local n_tile_idx = (tile_tbl[n_tile_x] or {})[n_tile_z]
                local n_tile = n_tile_idx ~= nil and self._tile_list[n_tile_idx] or nil
                local s_tile_x = this_node.x + self._tile_size*((joint_idx - 1)%3 - 1)
                local s_tile_z = this_node.z - self._tile_size
                local s_tile_idx = (tile_tbl[s_tile_x] or {})[s_tile_z]
                local s_tile = s_tile_idx ~= nil and self._tile_list[s_tile_idx] or nil
                if (n_tile == nil or not n_tile.joint[2]) and (s_tile == nil or not s_tile.joint[8]) then
                    joint[joint_idx] = true
                end
            end

            local edge_tbl = {}
            for joint_idx, _ in pairs(joint) do
                local next_node_x = this_node.x + (self._tile_size*2)*((joint_idx - 1)%3 - 1)
                local next_node_z = this_node.z + (self._tile_size*2)*((joint_idx - 1)//3 - 1)
                local next_node_idx = (node_tbl[next_node_x] or {})[next_node_z]
                if next_node_idx ~= nil then
                    local next_node = self._node_list[next_node_idx]
                    edge_tbl[next_node_idx] = math.sqrt((next_node.x - this_node.x)^2 + (next_node.z - this_node.z)^2)
                end
            end
            this_node.edge_tbl = edge_tbl
        end
    end

    function pf:_reset()
        self._start_node_idx = nil
        self._end_node_idx = nil

        for node_idx = self._num_perm_node + 1, #self._node_list do
            self._node_list[node_idx] = nil
        end
        for _, this_node in pairs(self._node_list) do
            this_node.cost = nil
            this_node.prev = nil
            this_node.visited = false

            for next_node_idx, _ in pairs(this_node.edge_tbl) do
                if next_node_idx > self._num_perm_node then
                    this_node.edge_tbl[next_node_idx] = nil
                end
            end
        end
    end

    function pf:_addTempNode(x, z)
        table.insert(self._node_list, {
            x = x,
            z = z,
            edge_tbl = {},
            cost = nil,
            prev = nil,
            visited = false,
        })
        local this_node_idx = #self._node_list
        local this_node = self._node_list[this_node_idx]

        local next_node_idx = nil
        local next_node = nil
        local next_cost = nil
        for node_idx, node in pairs(self._node_list) do
            if node_idx == this_node_idx then
                goto continue
            end

            local cost = math.sqrt((node.x - this_node.x)^2 + (node.z - this_node.z)^2)
            if next_cost == nil or cost < next_cost then
                next_node_idx = node_idx
                next_node = node
                next_cost = cost
            end

            ::continue::
        end
        if next_node_idx ~= nil then
            this_node.edge_tbl[next_node_idx] = next_cost
            next_node.edge_tbl[this_node_idx] = next_cost
        end

        local tile_x = math.floor(x/(self._tile_size*2) + 0.5)*(self._tile_size*2)
        local tile_z = math.floor(z/(self._tile_size*2) + 0.5)*(self._tile_size*2)
        if self._world_x1 <= tile_x and tile_x <= self._world_x2 and self._world_z1 <= tile_z and tile_z <= self._world_z2 then
            local tile = nil
            for _, loop_tile in pairs(self._tile_list) do
                if loop_tile.x == tile_x and loop_tile.z == tile_z then
                    tile = loop_tile
                    break
                end
            end
            if tile ~= nil then
                goto continue
            end

            for next_node_idx, next_node in pairs(self._node_list) do
                if next_node_idx ~= this_node_idx and math.abs(next_node.x - tile_x) <= self._tile_size and math.abs(next_node.z - tile_z) <= self._tile_size then
                    local cost = math.sqrt((next_node.x - this_node.x)^2 + (next_node.z - this_node.z)^2)
                    this_node.edge_tbl[next_node_idx] = cost
                    next_node.edge_tbl[this_node_idx] = cost
                end
            end

            ::continue::
        end

        for next_node_idx, next_node in pairs(self._node_list) do
            if (next_node_idx == this_node_idx) or self:_testRectAndLineCollision(
                self._world_x1 - self._tile_size + 1,
                self._world_z1 - self._tile_size + 1,
                self._world_x2 + self._tile_size - 1,
                self._world_z2 + self._tile_size - 1,
                this_node.x,
                this_node.z,
                next_node.x,
                next_node.z
            ) then
                goto continue
            end

            local cost = math.sqrt((next_node.x - this_node.x)^2 + (next_node.z - this_node.z)^2)
            this_node.edge_tbl[next_node_idx] = cost
            next_node.edge_tbl[this_node_idx] = cost

            ::continue::
        end

        return this_node_idx
    end

    function pf:_testRectAndLineCollision(rect_x1, rect_y1, rect_x2, rect_y2, line_x1, line_y1, line_x2, line_y2)
        return (
            (rect_x1 < line_x1 and line_x1 < rect_x2 and rect_y1 < line_y1 and line_y1 < rect_y2) or
            (rect_x1 < line_x2 and line_x2 < rect_x2 and rect_y1 < line_y2 and line_y2 < rect_y2) or
            self:_testLineAndLineCollision(rect_x1, rect_y1, rect_x1, rect_y2, line_x1, line_y1, line_x2, line_y2) or
            self:_testLineAndLineCollision(rect_x1, rect_y2, rect_x2, rect_y2, line_x1, line_y1, line_x2, line_y2) or
            self:_testLineAndLineCollision(rect_x2, rect_y2, rect_x2, rect_y1, line_x1, line_y1, line_x2, line_y2) or
            self:_testLineAndLineCollision(rect_x2, rect_y1, rect_x1, rect_y1, line_x1, line_y1, line_x2, line_y2)
        )
    end

    function pf:_testLineAndLineCollision(x11, y11, x12, y12, x21, y21, x22, y22)
        local x1211 = x12 - x11
        local y1211 = y12 - y11
        local x2111 = x21 - x11
        local y2111 = y21 - y11
        local x2211 = x22 - x11
        local y2211 = y22 - y11
        local x2221 = x22 - x21
        local y2221 = y22 - y21
        local x1121 = x11 - x21
        local y1121 = y11 - y21
        local x1221 = x12 - x21
        local y1221 = y12 - y21
        return (
            (((x1211*y2111 - x2111*y1211) * (x1211*y2211 - x2211*y1211)) < 0) and
            (((x2221*y1121 - x1121*y2221) * (x2221*y1221 - x1221*y2221)) < 0)
        )
    end

    function pf:_calcPath()
        for _, node in pairs(self._node_list) do
            node.cost = nil
            node.prev = nil
            node.visited = false
        end

        if self._node_list[self._start_node_idx] == nil then
            return
        end
        self._node_list[self._start_node_idx].cost = 0

        local heap = {}
        self:_heapPush(heap, self._start_node_idx, 0)
        while true do
            local this_node_idx = self:_heapPop(heap)
            if this_node_idx == nil then
                break
            end
            local this_node = self._node_list[this_node_idx]
            if this_node.visited then
                goto continue
            end
            this_node.visited = true
            if this_node_idx == self._end_node_idx then
                break
            end

            for next_node_idx, cost in pairs(this_node.edge_tbl) do
                local next_node = self._node_list[next_node_idx]
                if next_node.cost == nil or this_node.cost + cost < next_node.cost then
                    next_node.cost = this_node.cost + cost
                    next_node.prev = this_node_idx
                    self:_heapPush(heap, next_node_idx, -next_node.cost)
                end
            end

            ::continue::
        end
    end

    function pf:_heapPush(heap, val, priority)
        table.insert(heap, {val = val, priority = priority})

        local idx = #heap
        while idx > 1 do
            local parent_idx = idx//2
            if heap[parent_idx].priority >= heap[idx].priority then
                break
            end

            local tmp = heap[parent_idx]
            heap[parent_idx] = heap[idx]
            heap[idx] = tmp
            idx = parent_idx
        end
    end

    function pf:_heapPop(heap)
        if #heap <= 0 then
            return nil
        end
        local ret = heap[1].val

        heap[1] = heap[#heap]
        table.remove(heap)

        local idx = 1
        while true do
            local child_idx = idx*2
            if child_idx > #heap then
                break
            end
            if child_idx + 1 <= #heap and heap[child_idx + 1].priority > heap[child_idx].priority then
                child_idx = child_idx + 1
            end
            if heap[child_idx].priority <= heap[idx].priority then
                break
            end

            local tmp = heap[child_idx]
            heap[child_idx] = heap[idx]
            heap[idx] = tmp
            idx = child_idx
        end
        return ret
    end

    function pf:_getPathList()
        local end_node_idx = self._end_node_idx
        local end_node = self._node_list[end_node_idx]
        if end_node == nil then
            return {}
        end

        local nearest_node_idx = nil
        local nearest_cost = nil
        for node_idx, node in pairs(self._node_list) do
            if not node.visited then
                goto continue
            end

            local cost = (node.x - end_node.x)^2 + (node.z - end_node.z)^2
            if nearest_cost == nil or cost < nearest_cost then
                nearest_node_idx = node_idx
                nearest_cost = cost
            end
            ::continue::
        end
        local this_node_idx = nearest_node_idx

        local path_list = {}
        while this_node_idx ~= nil and this_node_idx ~= self._start_node_idx do
            local this_node = self._node_list[this_node_idx]
            table.insert(path_list, 1, {x = this_node.x, z = this_node.z})
            this_node_idx = this_node.prev
        end
        return path_list
    end

    pf:_init()
    return pf
end
